modLoader = "javafml"

loaderVersion = "[47,)"

license = "MIT"

[[mods]]
modId = "invertedbed"

version = "${mod_version}"

displayName = "${mod_name}"

authors = "${mod_authors}"

description = '''A mod that adds an inverted bed to sleep during the day'''

[[dependencies.invertedbed]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invertedbed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"